# Generated by Django 5.2.4 on 2025-11-02 09:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('game', 'Game'), ('training', 'Training'), ('tournament', 'Tournament')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField(default=datetime.time(12, 0))),
                ('location', models.CharField(default='Unknown', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('repeat', models.CharField(choices=[('none', 'Does not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 Weeks'), ('monthly', 'Monthly')], default='none', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('item_type', models.CharField(choices=[('jersey', 'Jersey'), ('cleats', 'Cleats'), ('shin_guard', 'Shin Guard'), ('ball', 'Ball'), ('other', 'Other')], default='other', max_length=50)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('worn', 'Worn'), ('unusable', 'Unusable')], default='good', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'main_equipment',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary')], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('jersey_number', models.PositiveIntegerField(unique=True)),
                ('position', models.CharField(choices=[('Striker', 'Striker'), ('Winger', 'Winger'), ('Midfielder', 'Midfielder'), ('Defender', 'Defender'), ('Goalkeeper', 'Goalkeeper')], max_length=50)),
                ('current_school', models.CharField(max_length=100)),
                ('initial_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InjuryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_injury', models.DateField(blank=True, null=True)),
                ('duration_type', models.CharField(choices=[('short', 'Short Term'), ('long', 'Long Term')], default='short', max_length=10)),
                ('injury_type', models.CharField(choices=[('muscle', 'Muscle Injury'), ('bone', 'Bone Injury'), ('joint', 'Joint Injury'), ('concussion', 'Concussion'), ('other', 'Other')], default='other', max_length=20)),
                ('injury_treatment', models.TextField()),
                ('recovery_date', models.DateField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('returned', models.BooleanField(default=False)),
                ('condition_when_issued', models.CharField(choices=[('good', 'Good'), ('worn', 'Worn'), ('unusable', 'Unusable')], default='good', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='main.inventoryitem')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(max_length=50)),
                ('average_score', models.FloatField(default=0)),
                ('passing', models.BooleanField(default=True)),
                ('school', models.CharField(blank=True, default='', max_length=255)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
        ),
    ]
